const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const MEMBER_REMOVED = "MEMBER_REMOVED";
const ONLINE_NOW = "ONLINE_NOW";
const OFFLINE_NOW = "OFFLINE_NOW";

module.exports = {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  MEMBER_REMOVED,
  ONLINE_NOW,
  OFFLINE_NOW,
};
